base_url: http://localhost:8080
exec_args: serve

data_dirs:
  - cmd/stv-poll/templates
  - cmd/stv-poll/static

http:
  secure_cookies: true
  read_header_timeout: 5s
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  shutdown_timeout: 10s
moderators: []

service:
  capabilities:
    local_mail: true

# timers:
#   - name: process-due-work
#     interval: 1min
#     args: [process-due-work]
